# Generated by Django 4.2.20 on 2025-04-16 15:56

from django.db import migrations, models
import django.db.models.deletion


def migrate_location_to_scope(apps, schema_editor):
    VLANGroup = apps.get_model("ipam", "VLANGroup")
    Location = apps.get_model("dcim", "Location")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Get ContentType for Location model
    location_ct = ContentType.objects.get_for_model(Location)

    for vlan_group in VLANGroup.objects.all():
        if vlan_group.location_id:
            vlan_group.scope_content_type = location_ct
            vlan_group.scope_object_id = vlan_group.location_id
            vlan_group.save(update_fields=["scope_content_type", "scope_object_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ipam", "0051_added_optional_vrf_relationship_to_vdc"),
    ]

    operations = [
        migrations.AddField(
            model_name="vlangroup",
            name="scope_content_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="vlangroup",
            name="scope_object_id",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(migrate_location_to_scope, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="vlangroup",
            name="location",
        ),
    ]
